language: cpp
git:
  depth: 100
notifications:
  email: false
matrix:
  include:
  - os: osx
    compiler: clang
    osx_image: xcode10.1
  - os: linux
    compiler: gcc
    dist: xenial
  - os: linux
    compiler: gcc
    dist: xenial
    env: COVERAGE="ON"
  - os: windows

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  sudo apt-get -y install xorg-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev;
  fi

script:
- mkdir build
- cd build
- if [[ "$COVERAGE" == "ON" ]]; then
  export CONFIG="Debug";
  else
  export CONFIG="Release";
  fi
- cmake -DBUILD_PENUMBRA_TESTING=ON -DPENUMBRA_COVERAGE="$COVERAGE" -DCMAKE_BUILD_TYPE="$CONFIG" ..
- cmake --build . --config Release
- ctest --output-on-failure -C Release
- if [[ "$COVERAGE" == "ON" ]]; then
  make gcov || travis_terminate 1;
  fi

after_success:
- if [[ "$COVERAGE" == "ON" ]]; then
  bash <(curl -s https://codecov.io/bash) -X gcov || travis_terminate 1;
  fi
