name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v1
    - name: configure
      env:
        CC: ${{ matrix.compiler }}
      run: 
        mkdir build
        cd build
        cmake -DBUILD_PENUMBRA_TESTING="$TESTING" -DPENUMBRA_STATIC_LIB="$STATIC_LIB" -DPENUMBRA_COVERAGE="$COVERAGE" -DCMAKE_BUILD_TYPE="$CONFIG" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest

  build-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v1
    - name: configure
      env:
        CC: ${{ matrix.compiler }}
      run: 
        mkdir build
        cd build
        cmake -DBUILD_PENUMBRA_TESTING="$TESTING" -DPENUMBRA_STATIC_LIB="$STATIC_LIB" -DPENUMBRA_COVERAGE="$COVERAGE" -DCMAKE_BUILD_TYPE="$CONFIG" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
