name: C/C++ CI

on: [push]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DBUILD_GMOCK="ON" -DBUILD_GTEST="ON" -DBUILD_PENUMBRA_TESTING="ON" -DPENUMBRA_STATIC_LIB="OFF" -DPENUMBRA_COVERAGE="OFF" -DCMAKE_BUILD_TYPE="Debug" ..
    - name: build
      run: |
        cmake --build .
    - name: test
      run: |
        ctest
