name: Build and Test

on: push

jobs:
  build-and-test:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        run: cmake -S . -B build
      - name: Build
        run: cmake --build ./build --config Release
      - name: Test
        run: ctest -C Release --output-on-failure
        working-directory: build